exports.seed = async function (knex) {
    await knex('categories').del();
    await knex('species').del();
    let categories = [
        {
            id: "a",
            categoryName: "Critically Endangered"
        },
        {
            id: "b",
            categoryName: "Endangered"
        },
        {
            id: "c",
            categoryName: "Vulnerable"
        },
        {
            id: "d",
            categoryName: "Near Threatened"
        }
    ];
    let species = [
        {
            id: 1,
            category_id: "a",
            name: "AFRICAN FOREST ELEPHANT",
            image: "",
            scientificName: "Loxodonta cyclotis",
            category: "Critically Endangered",
            population: "415,000",
            habitat: "dense tropical forests",
            information: "African forest elephants are the elusive cousin of the African savanna elephant. They inhabit the dense rainforests of west and central Africa. Their preference for dense forest habitat prohibits traditional counting methods such as visual identification. Their population is usually estimated through 'dung counts'—an analysis on the ground of the density and distribution of the feces. \nAfrican forest elephants are smaller than African savanna elephants, the other African elephant species. Their ears are more oval-shaped and their tusks are straighter and point downward (the tusks of savanna elephants curve outwards). There are also differences in the size and shape of the skull and skeleton. Forest elephants also have a much slower reproductive rate than savanna elephants, so they cannot bounce back from population declines as quickly at the same rate. Their last strongholds are located in Gabon and the Republic of Congo, with smaller populations remaining in other African countries (Cameroon, Central African Republic, Equatorial Guinea) and Côte d'Ivoire, Liberia, and Ghana in west Africa. \nAfrican forest elephants live in family groups of up to 20 individuals and forage on leaves, grasses, seeds, fruit, and tree bark. Since the diet of forest elephants is dominated by fruit, they play a crucial role in dispersing many tree species, particularly the seeds of large trees which tend to have high carbon content. They are therefore referred to as the 'mega-gardener of the forest'. To supplement their diet with minerals, they gather at mineral-rich waterholes and mineral licks found throughout the forest.",
            source: "worldwildlife.org",
            petition: "https://support.worldwildlife.org/site/Advocacy?cmd=display&page=UserAction&id=664&_ga=2.58641642.138606632.1655935991-1703178925.1655935991",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/African-Elephant.aspx?sc=AWY1800OQ18317A01909RX&_ga=2.29802751.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 2,
            category_id: "a",
            name: "AMUR LEOPARD",
            image: "",
            scientificName: "Panthera pardus orientalis",
            category: "Critically Endangered",
            population: "120",
            habitat: "temperate, broadleaf, and mixed forests",
            information: "People usually think of leopards in the savannas of Africa but in the Russian Far East, a rare subspecies has adapted to life in the temperate forests that make up the northern-most part of the species’ range. Similar to other leopards, the Amur leopard can run at speeds of up to 37 miles per hour. This incredible animal has been reported to leap more than 19 feet horizontally and up to 10 feet vertically. \nThe Amur leopard is solitary. Nimble-footed and strong, it carries and hides unfinished kills so that they are not taken by other predators. It has been reported that some males stay with females after mating, and may even help with rearing the young. Several males sometimes follow and fight over a female. They live for 10-15 years, and in captivity up to 20 years. The Amur leopard is also known as the Far East leopard, the Manchurian leopard or the Korean leopard.",
            source: "worldwildlife.org",
            petition: "https://therainforestsite.greatergood.com/clicktogive/trs/petition/amur-leopards",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Amur-Leopard.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.34516065.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 3,
            category_id: "a",
            name: "BLACK RHINO",
            image: "",
            scientificName: "Diceros bicornis",
            category: "Critically Endangered",
            population: "5,500",
            habitat: "semi-desert savannah, woodlands, forests, wetlands",
            information: "Black rhinos are the smaller of the two African rhino species. The most notable difference between white and black rhinos are their hooked upper lip. This distinguishes them from the white rhino, which has a square lip. Black rhinos are browsers rather than grazers, and their pointed lip helps them feed on leaves from bushes and trees. They have two horns, and occasionally a third, small posterior horn. \nPopulations of black rhino declined dramatically in the 20th century at the hands of European hunters and settlers. Between 1960 and 1995, black rhino numbers dropped by a sobering 98%, to less than 2,500. Since then, the species has made a tremendous comeback from the brink of extinction. Thanks to persistent conservation efforts across Africa, black rhino numbers have doubled from their historic low 20 years ago to around 5,500 today. However, the black rhino is still considered critically endangered, and a lot of work remains to bring the numbers up to even a fraction of what it once was—and to ensure that it stays there. Wildlife crime—in this case, poaching and black-market trafficking of rhino horn—continues to plague the species and threaten its recovery.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/732/788/318/?TAP=1732",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/African-Rhino.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.268431182.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 4,
            category_id: "a",
            name: "BORNEAN ORANGUTAN",
            image: "",
            scientificName: "Pongo pygmaeus",
            category: "Critically Endangered",
            population: "104,700",
            habitat: "lowland rainforests and tropical, swamp and mountain forests",
            information: "Bornean orangutan populations have declined by more than 50% over the past 60 years, and the species' habitat has been reduced by at least 55% over the past 20 years. \nThe Bornean orangutan differs in appearance from the Sumatran orangutan, with a broader face and shorter beard and also slightly darker in color. Three subspecies are recognized, each localized to different parts of the island: \nNorthwest Bornean orangutans are the most threatened subspecies. Its habitat has been seriously affected by logging and hunting, and a mere 1,500 individuals or so remain. Many habitat patches in the area are small and fragmented. \nNortheast Bornean orangutans are the smallest in size and found in Sabah and eastern Kalimantan as far as the Mahakam River. \nCentral Bornean orangutans are the subspecies with the most animals, with at least 35,000 individuals.",
            source: "worldwildlife.org",
            petition: "https://preserve.nature.org/page/81901/petition/1",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Female-Orangutan.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.95923036.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 5,
            category_id: "a",
            name: "CROSS RIVER GORILLA",
            image: "",
            scientificName: "Gorilla gorilla diehli",
            category: "Critically Endangered",
            population: "200 to 300",
            habitat: "lowland montane forests and rainforests",
            information: "This subspecies of the western gorilla is very similar in appearance to the more numerous western lowland gorilla, but subtle differences can be found in the skull and tooth dimensions. Cross River gorillas live in a region populated by many humans who have encroached upon the gorilla’s territory—clearing forests for timber and to create fields for agriculture and livestock. Poaching occurs in the forests as well, and the loss of even a few of these gorillas has a detrimental effect on such a small population. \nEfforts to protect these animals are focused on securing the forests that house them. WWF and partners have worked with the governments of Cameroon and Nigeria to create a protected area for the Cross River gorilla that spans the border of these two nations.",
            source: "worldwildlife.org",
            petition: "https://www.play4forests.org/en",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Gorilla.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.256222411.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 6,
            category_id: "a",
            name: "EASTERN LOWLAND GORILLA",
            image: "",
            scientificName: "Gorilla beringei graueri",
            category: "Critically Endangered",
            population: "3,800",
            habitat: "lowland tropical rainforests",
            information: "The eastern lowland gorilla—also known as Grauer’s gorilla—is the largest of the four gorilla subspecies. It is distinguished from other gorillas by its stocky body, large hands and short muzzle. Despite its size, eastern lowland gorillas subsist mainly on fruit and other herbaceous materials, just like other gorilla subspecies. \nYears of civil unrest in the Democratic Republic of Congo (DRC) have taken their toll on both the eastern lowland gorilla and the mountain gorilla. The eastern lowland gorilla makes its home in lowland tropical rainforests in the eastern DRC. In the last 50 years, its range has decreased from 8,100 square miles—about the size of the state of Massachusetts— to about 4,600 square miles today. This subspecies may now occupy only 13% of its historical range. There were nearly 17,000 eastern lowland gorillas in the mid-1990s but scientists estimate that the population has declined by more than 50% since then. An accurate accounting of the animals has been impossible for many years because of violence in the region. \nThroughout the unrest, the gorillas have been vulnerable to poaching, even in Kahuzi-Biega National Park, home to the largest population of protected eastern lowland gorillas. Rebels and poachers invaded the park and people set up illegal mines. But, with help from WWF and other organizations, park staff are reestablishing control over the land.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/use-your-phones-to-save-our-gorillas",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Gorilla.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.264143820.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 7,
            category_id: "a",
            name: "HAWKSBILL TURTLE",
            image: "",
            scientificName: "Eretmochelys imbricata",
            category: "Critically Endangered",
            population: "25,000",
            habitat: "oceans",
            information: "Hawksbills are named for their narrow, pointed beak. They also have a distinctive pattern of overlapping scales on their shells that form a serrated-look on the edges. These colored and patterned shells make them highly-valuable and commonly sold as 'tortoiseshell' in markets. \nHawksbills are found mainly throughout the world's tropical oceans, predominantly in coral reefs. They feed mainly on sponges by using their narrow pointed beaks to extract them from crevices on the reef, but also eat sea anemones and jellyfish. Sea turtles are the living representatives of a group of reptiles that has existed on Earth and travelled our seas for the last 100 million years. They are a fundamental link in marine ecosystems and help maintain the health of coral reefs and sea grass beds.",
            source: "worldwildlife.org",
            petition: "https://therainforestsite.greatergood.com/clicktogive/trs/petition/hawksbill-sea-turtles",
            donate: "https://www.seeturtles.org/save-the-turtles"
        },
        {
            id: 8,
            category_id: "a",
            name: "JAVAN RHINO",
            image: "",
            scientificName: "Rhinoceros sondaicus",
            category: "Critically Endangered",
            population: "60",
            habitat: "tropical forests",
            information: "Javan rhinos are the most threatened of the five rhino species, with only around 60 individuals that live only in Ujung Kulon National Park in Java, Indonesia. Javan rhinos once lived throughout northeast India and Southeast Asia. Vietnam’s last Javan rhino was poached in 2010. \nThis species is a dusky grey color and has a single horn of up to about 10 inches. Its skin has a number of loose folds, giving the appearance of armor plating. The Javan rhino is very similar in appearance to the closely-related greater one-horned rhinoceros, but has a much smaller head and less apparent skin folds.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/798/545/460/save-critically-endangered-javan-rhino/",
            donate: "https://rhinos.org/adopt/adopt-a-javan-rhino/"
        },
        {
            id: 9,
            category_id: "a",
            name: "SAOLA",
            image: "",
            scientificName: "Pseudoryx nghetinhensis",
            category: "Critically Endangered",
            population: "250",
            habitat: "evergreen forests with little or no dry season",
            information: "The saola was discovered in May 1992 during a joint survey carried out by the Ministry of Forestry of Vietnam and WWF in north-central Vietnam. The team found a skull with unusual long, straight horns in a hunter's home and knew it was something extraordinary. The find proved to be the first large mammal new to science in more than 50 years and one of the most spectacular zoological discoveries of the 20th century. \nSaola (pronounced: sow-la) are recognized by two parallel horns with sharp ends, which can reach 20 inches in length and are found on both males and females. Meaning “spindle horns” in Vietnamese, they are a cousin of cattle but resemble an antelope. Saola have striking white markings on the face and large maxillary glands on the muzzle, which could be used to mark territory or attract mates. They are found only in the Annamite Mountains of Vietnam and Laos.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/177/913/573/save-the-saola/",
            donate: "https://www.rewild.org/wild-about/saola"
        },
        {
            id: 10,
            category_id: "a",
            name: "SUMATRAN ELEPHANT",
            image: "",
            scientificName: "Elephas maximus sumatranus",
            category: "Critically Endangered",
            population: "2,400 - 2,800",
            habitat: "broadleaf moist tropical forests",
            information: "Sumatran elephants feed on a variety of plants and deposit seeds wherever they go, contributing to a healthy forest ecosystem. They also share their lush forest habitat with several other endangered species, such as the Sumatran rhino, tiger, and orangutan, and countless other species that all benefit from an elephant population that thrives in a healthy habitat.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/takeaction/292/436/940/",
            donate: "https://ptes.org/grants/worldwide-projects/sumatran-elephants-in-indonesia/"
        },
        {
            id: 11,
            category_id: "a",
            name: "SUMATRAN ORANGUTAN",
            image: "",
            scientificName: "Pongo abelii",
            category: "Critically Endangered",
            population: "14,613",
            habitat: "tropical and subtropical moist broadleaf forests",
            information: "The Sumatran orangutan is almost exclusively arboreal, living among the trees of tropical rainforests. Females virtually never travel on the ground and adult males do so rarely. Sumatran orangutans are reported to have closer social ties than their Bornean cousins. This has been attributed to mass fruit on fig trees, where groups of Sumatran orangutans can come together to feed. Adult males are typically solitary while females are accompanied by offspring. \nHistorically, the Sumatran orangutan was distributed over the entire island of Sumatra and further south into Java. The species' range is now restricted to the north of the island with a majority in the provinces of North Sumatra and Aceh. Of the nine existing populations of Sumatran orangutans, only seven have prospects of long-term viability, each with an estimated 250 or more individuals. Only three populations contain more than 1,000 orangutans. Orangutans that were confiscated from the illegal trade or as pets are being reintroduced to Bukit Tigapuluh National Park. They number around 70 and are reproducing.",
            source: "worldwildlife.org",
            petition: "https://actionnetwork.org/petitions/urgent-stop-destroying-critical-orangutan-habitat-jardine-matheson",
            donate: "https://www.sumatranorangutan.org/donate/"
        },
        {
            id: 12,
            category_id: "a",
            name: "SUMATRAN RHINO",
            image: "",
            scientificName: "Dicerorhinus sumatrensis",
            category: "Critically Endangered",
            population: "80",
            habitat: "dense highland and lowland tropical and sub-tropical forests",
            information: "Sumatran rhinos are the smallest of the living rhinoceroses and the only Asian rhino with two horns. They are covered with long hair and are more closely related to the extinct woolly rhinos than any of the other rhino species alive today. Calves are born with a dense covering that turns reddish-brown in young adults and becomes sparse, bristly and almost black in older animals. Sumatran rhinos compete with the Javan rhino for the unenviable title of most threatened rhino species. While surviving in possibly greater numbers than the Javan rhino, Sumatran rhinos are more threatened due to habitat loss and fragmentation. The remaining animals survive in small, fragmented non-viable populations, and with limited possibilities to find each other to breed, its population decline continues. Just two captive females have reproduced in the last 15 years. \nThe Sumatran rhino once roamed as far away as the foothills of the Eastern Himalayas in Bhutan and eastern India, through Myanmar, Thailand, possibly to Vietnam and China, and south through the Malay Peninsula. Today, the species only survives on the Indonesian islands of Sumatra and Borneo. Experts believe the third subspecies is probably extinct.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/941/658/570/act-now-to-save-the-sumatran-rhino/",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Sumatran-Rhino.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.188664680.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 13,
            category_id: "a",
            name: "SUNDA TIGER",
            image: "",
            scientificName: "Panthera tigris sondaica",
            category: "Critically Endangered",
            population: "Less than 400",
            habitat: "tropical broadleaf evergreen forests, freshwater swamp forests and peat swamps",
            information: "Sunda tigers are distinguished by heavy black stripes on their orange coats. The last of the Sunda island tigers—estimated to be fewer than 400 today—are holding on for survival in the remaining patches of forest on the island of Sumatra. Accelerating deforestation and rampant poaching mean this noble creature could end up extinct like its Javan and Balinese counterparts. \nIn Indonesia, anyone caught hunting tigers could face jail time and steep fines. But despite increased efforts in tiger conservation—including strengthening law enforcement and antipoaching capacity—a substantial market remains in Sumatra and other parts of Asia for tiger parts and products. Sunda tigers are losing their habitat and prey fast, and poaching is an ever-present threat.",
            source: "worldwildlife.org",
            petition: "https://therainforestsite.greatergood.com/clicktogive/trs/petition/sumatran-tigers",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Tiger.aspx"
        },
        {
            id: 14,
            category_id: "a",
            name: "VAQUITA",
            image: "",
            scientificName: "Phocoena sinus",
            category: "Critically Endangered",
            population: "10",
            habitat: "marine (only in the northern Gulf of California)",
            information: "Vaquita, the world's rarest marine mammal, is on the edge of extinction. The plight of cetaceans—whales, dolphins, and porpoises—as a whole is exemplified by the rapid decline of the vaquita in Mexico, with about 10 individuals remaining. This little porpoise wasn't discovered until 1958 and a little over half a century later, we are on the brink of losing them forever. Vaquita are often caught and drowned in gillnets used by illegal fishing operations in marine protected areas within Mexico's Gulf of California. The population has dropped drastically in the last few years. \nThe vaquita has a large dark ring around its eyes and dark patches on its lips that form a thin line from the mouth to the pectoral fins. Its top—the dorsal surface—is dark gray, its sides are pale gray, and its underside—the ventral surface—is white with long, light gray markings. Newborn vaquita have darker coloration and a wide gray fringe of color that runs from the head to the flukes, passing through the dorsal and pectoral fins. They are most often found close to shore in the Gulf's shallow waters, although they quickly swim away if a boat approaches.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/save-mexico-s-vaquita-porpoise-from-imminent-extinction",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Vaquita.aspx"
        },
        {
            id: 15,
            category_id: "a",
            name: "WESTERN LOWLAND GORILLA",
            image: "",
            scientificName: "Gorilla gorilla gorilla",
            category: "Critically Endangered",
            population: "4,000",
            habitat: "dense rainforests",
            information: "The western lowland gorilla is the most numerous and widespread of all gorilla subspecies. Populations can be found in Cameroon, the Central African Republic, the Democratic Republic of Congo and Equatorial Guinea as well as in large areas in Gabon and the Republic of Congo. The exact number of western lowland gorillas is not known because they inhabit some of the most dense and remote rainforests in Africa. Significant populations still exist, including in isolated swamps and the remote swampy forests of the Republic of Congo. \nWestern lowland gorillas can be distinguished from other gorilla subspecies by their slightly smaller size, their brown-grey coats and auburn chests. They also have wider skulls with more pronounced brow ridges and smaller ears. Large numbers have not protected the western lowland gorilla from decline. Because of poaching and disease, the gorilla’s numbers have declined by more than 60% over the last 20 to 25 years. Even if all of the threats to western lowland gorillas were removed, scientists calculate that the population would require some 75 years to recover.",
            source: "worldwildlife.org",
            petition: "https://www.rainforest-rescue.org/petitions/1188/nigeria-keep-cocoa-growers-out-of-gorilla-habitat#letter",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Gorilla.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.188530920.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 16,
            category_id: "a",
            name: "YANGTZE FINLESS PORPOISE",
            image: "",
            scientificName: "Neophocaena asiaeorientalis",
            category: "Critically Endangered",
            population: "1,000 - 1,800",
            habitat: "dense rainforests",
            information: "The Yangtze River, the longest river in Asia, used to be one of the only two rivers in the world that was home to two different species of dolphin—the Yangtze finless porpoise and the Baiji dolphin. However, in 2006 the Baiji dolphin was declared functionally extinct. This was the first time in history that an entire species of dolphin had been wiped off the planet because of human activity. Its close cousin, the Yangtze finless porpoise, is known for its mischievous smile and has a level of intelligence comparable to that of a gorilla.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/257/675/391/sos-yangtze-finless-porpoise-appeal-for-international-help/",
            donate: "https://give.porpoise.org/gift/adopt-a-finless-porpoise/"
        },
        {
            id: 17,
            category_id: "b",
            name: "AFRICAN WILD DOG",
            image: "",
            scientificName: "Lycaon pictus",
            category: "Endangered",
            population: "1,409",
            habitat: "deserts, forests, grasslands",
            information: "The wild dog is one of the world’s most endangered mammals. The largest populations remain in southern Africa and the southern part of East Africa (especially Tanzania and northern Mozambique). \nWild dogs are social and gather in packs of around ten individuals, but some packs number more than 40. They are opportunistic predators that hunt medium-sized ruminants, such as gazelles. In a sprint, African wild dogs can reach speeds of more than 44 miles per hour.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/animal-lovers-and-wildlife-rescuers-make-an-insurance-population-of-african-wild-dogs-in-the-washington-dc-national-zoo",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/African-Wild-Dog.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.256624715.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 18,
            category_id: "b",
            name: "ASIAN ELEPHANT",
            image: "",
            scientificName: "Elephas maximus indicus",
            category: "Endangered",
            population: "Fewer than 50,000",
            habitat: "forests",
            information: "The Asian elephant is the largest land mammal on the Asian continent. They inhabit dry to wet forest and grassland habitats in 13 range countries spanning South and Southeast Asia. While they have preferred forage plants, Asian elephants have adapted to surviving on resources that vary based on the area. \nAsian elephants are extremely sociable, forming groups of six to seven related females that are led by the oldest female, the matriarch. Like African elephants, these groups occasionally join others to form larger herds, although these associations are relatively short-lived. In Asia, elephant herd sizes are significantly smaller than those of savannah elephants in Africa. \nMore than two-thirds of an elephant's day may be spent feeding on grasses, but it also eats large amounts of tree bark, roots, leaves, and small stems. Cultivated crops such as bananas, rice, and sugarcane are favorite foods. Elephants are always close to a source of fresh water because they need to drink at least once a day. \nIn Asia, humans have had close associations with elephants over many centuries, and elephants have become important cultural icons. According to Hindu mythology, the gods (deva) and the demons (asura) churned the oceans in a search for the elixir of life so that they would become immortal. As they did so, nine jewels surfaced, one of which was the elephant. In Hinduism, the powerful deity honored before all sacred rituals is the elephant-headed Lord Ganesha, who is also called the Remover of Obstacles.",
            source: "worldwildlife.org",
            petition: "https://support.worldwildlife.org/site/Advocacy?cmd=display&page=UserAction&id=664&_ga=2.21997051.138606632.1655935991-1703178925.1655935991",
            donate: "https://saveelephant.org/"
        },
        {
            id: 19,
            category_id: "b",
            name: "BLACK-FOOTED FERRET",
            image: "",
            scientificName: "Mustela nigripes",
            category: "Endangered",
            population: "370",
            habitat: "grasslands",
            information: "Saving rare species from extinction requires extraordinary measures. The black-footed ferret is one of North America’s most endangered mammals. Once thought to be extinct, after the species was rediscovered in Wyoming in 1981, concerted efforts by numerous partners have given black-footed ferrets a second chance for survival. Captive breeding, reintroductions, habitat protection, and cloning have helped restore them to over 300 animals in the wild. Although great strides have been made to recover the black-footed ferret, habitat loss and disease remain their key threats. Biologists estimate that there should be 3,000 adult ferrets in the wild to successfully recover this endangered species.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/world-wildlife-fund-save-the-black-footed-ferret",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Black-footed-Ferret.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.264732879.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 20,
            category_id: "b",
            name: "BLUE WHALE",
            image: "",
            scientificName: "Balaenoptera musculus",
            category: "Endangered",
            population: "10,000 - 25,000",
            habitat: "oceans",
            information: "The blue whale is the largest animal on the planet, weighing as much as 200 tons (approximately 33 elephants). The blue whale has a heart the size of a Volkswagen Beetle. Its stomach can hold one ton of krill and it needs to eat about four tons of krill each day. They are the loudest animals on Earth and are even louder than a jet engine. Their calls reach 188 decibels, while a jet reaches 140 decibels. Their low frequency whistle can be heard for hundreds of miles and is probably used to attract other blue whales.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/austin-save-the-blue-whale",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Blue-Whale.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.20889720.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 21,
            category_id: "b",
            name: "BLUEFIN TUNA",
            image: "",
            scientificName: "Thunnus Thynnus",
            category: "Endangered",
            population: "1 million",
            habitat: "oceans",
            information: "Bluefin are the largest tunas and can live up to 40 years. They migrate across all oceans and can dive deeper than 3,000 feet. Bluefin tuna are made for speed: built like torpedoes, have retractable fins and their eyes are set flush to their body. They are tremendous predators from the moment they hatch, seeking out schools of fish like herring, mackerel, and even eels. They hunt by sight and have the sharpest vision of any bony fish. There are three species of bluefin: Atlantic (the largest and most endangered), Pacific, and Southern. Most catches of the Atlantic bluefin tuna are taken from the Mediterranean Sea, which is the most important bluefin tuna fishery in the world.",
            source: "worldwildlife.org",
            petition: "https://therainforestsite.greatergood.com/clicktogive/trs/petition/Atlantic-Bluefin-Tuna",
            donate: "https://www.sailorsforthesea.org/programs/ocean-watch/protecting-bluefin-tuna"
        },
        {
            id: 22,
            category_id: "b",
            name: "BONOBO",
            image: "",
            scientificName: "Pan paniscus",
            category: "Endangered",
            population: "10,000 to 50,000",
            habitat: "forests south of the Congo River",
            information: "Bonobos and chimpanzees look very similar and both share 98.7% of their DNA with humans—making the two species our closest living relatives. Bonobos are usually a bit smaller, leaner and darker than chimpanzees. Their society is also different—bonobo groups tend to be more peaceful and are led by females. They also maintain relationships and settle conflicts through sex. However, bonobo life isn’t entirely violence free; if two groups of bonobos come together, they may engage in serious fighting. \nWild bonobos can only be found in forests south of the Congo River in the Democratic Republic of Congo (DRC). Sometimes known as the pygmy chimpanzee, bonobos weren’t recognized as a separate species until 1929. As the last great ape to be scientifically described, much remains unknown about the bonobo—including the extent of its geographic range. Efforts to survey the species over the past two decades have been hampered by the remote nature of its habitat, the patchiness of their distribution and years of civil unrest within the DRC. \nCivil unrest and increasing poverty in the area around the bonobos’ forests have contributed to bonobo poaching and deforestation. Though the size of the bonobo population is largely unknown, it has likely been declining for the last 30 years. Scientists believe that the decline will continue for the next 45 to 55 years due to the bonobo’s low reproductive rate and growing threats.",
            source: "worldwildlife.org",
            petition: "https://pasa.org/letter-to-end-social-media-support/",
            donate: "https://pasa.org/help-us-save-lives/"
        },
        {
            id: 23,
            category_id: "b",
            name: "BORNEAN ELEPHANT",
            image: "",
            scientificName: "Elephas maximus borneensis",
            category: "Endangered",
            population: "Less than 1,500",
            habitat: "forests",
            information: "The smallest Asian elephant subspecies, Bornean elephants are distinctly smaller than their mainland cousins. They have long tails that sometimes touch the ground, relatively large ears, and straighter tusks. While they are also known as Borneo pygmy elephants due to their smaller size, at 8.2-9.8 feet tall, the Bornean elephant is the largest mammal on the island. \nOnce believed to be remnants of a domesticated herd given to the Sultan of Sulu in the 17th century, Bornean elephants were determined by WWF to be genetically different from other Asian elephants. DNA evidence proved that these elephants were isolated about 300,000 years ago from their cousins on mainland Asia and Sumatra.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/168/024/211/protect-the-borneo-pygmy-elephant/",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Pygmy-Elephant.aspx?sc=AWY1800OQ18317A01909RX&_ga=2.58704874.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 24,
            category_id: "b",
            name: "CHIMPANZEE",
            image: "",
            scientificName: "Pan troglodytes",
            category: "Endangered",
            population: "172,700 to 299,700",
            habitat: "moist and dry forests, savannah woodlands, grassland-forest mosaics",
            information: "Like us, chimps are highly social animals, care for their offspring for years and can live to be over 50. In fact, chimpanzees are our closest cousins; we share about 98% of our genes. \nIn their habitat in the forests of Central Africa, chimpanzees spend most of their days in the treetops. When they do come down to earth, chimps usually travel on all fours, though they can walk on their legs like humans for as far as a mile. They use sticks to fish termites out of mounds and bunches of leaves to sop up drinking water.",
            source: "worldwildlife.org",
            petition: "https://freedomforgreatapes.org/petition/",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Chimpanzee.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.30926719.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 25,
            category_id: "b",
            name: "FIN WHALE",
            image: "",
            scientificName: "Balaenoptera physalus",
            category: "Endangered",
            population: "50,000 - 90,000",
            habitat: "oceans",
            information: "Some scientists have speculated that fin whales circle schools of fish with the white side facing the prey and frightening them into denser schools that are easier for the whale to catch. The fin whale, like other baleen whales, strains its food from the water through baleen plates. \nNext to the blue whale, the fin whale is the second largest mammal in the world. They have a distinct ridge along their back behind the dorsal fin, which gives it the nickname 'razorback'. Fin whales have a very unusual feature: the lower right jaw is bright white and the lower left jaw is black.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/525/872/281/tell-iceland-not-to-resume-fin-whale-hunt/",
            donate: "https://savethewhales.org/fin-whale/"
        },
        {
            id: 26,
            category_id: "b",
            name: "GALÁPAGOS PENGUIN",
            image: "",
            scientificName: "Spheniscus mendiculus",
            category: "Endangered",
            population: "Less than 2,000",
            habitat: "oceans",
            information: "The Galapagos Penguin is the smallest South American penguin, and the only one to live near the equator. It shares the Galápagos Archipelago with other seabirds such as the Galapagos Petrel and Waved Albatross. It is the most northerly-breeding penguin species in the world, living around the equator. In fact, a small part of the population actually lives just north of the equator. This species is closely related to Magellanic, Humboldt, and African Penguins, which are found further south, although none of these are Antarctic. \nThe Galapagos Penguin has a number of physical and behavioral adaptations that help it keep cool. Its small size — no more than 20 inches in height — allows it to squeeze into small caves and crevasses to hide from the strong equatorial sun. In addition, bare patches on its face and behaviors such as panting and standing with flippers extended also help it to release heat.",
            source: "abcbirds.org",
            petition: "https://www.thepetitionsite.com/432/686/980/save-the-galapagos-penguin/",
            donate: "https://www.galapagos.org/conservation/our-work/ecosystem-restoration/increasing-the-galapagos-penguin-population/"
        },
        {
            id: 27,
            category_id: "b",
            name: "GANGES RIVER DOLPHIN",
            image: "",
            scientificName: "Platanista gangetica gangetica",
            category: "Endangered",
            population: "3,500 - 5,000",
            habitat: "freshwater rivers",
            information: "Dolphins are one of the oldest creatures in the world along with some species of turtles, crocodiles and sharks. The Ganges river dolphin was officially discovered in 1801. Ganges river dolphins once lived in the Ganges-Brahmaputra-Meghna and Karnaphuli-Sangu river systems of Nepal, India, and Bangladesh. But the species is extinct from most of its early distribution ranges. \nThe Ganges river dolphin can only live in freshwater and is essentially blind. They hunt by emitting ultrasonic sounds, which bounces off of fish and other prey, enabling them to “see” an image in their mind. They are frequently found alone or in small groups, and generally a mother and calf travel together. Calves are chocolate brown at birth and then have grey-brown smooth, hairless skin as adults. Females are larger than males and give birth once every two to three years to only one calf.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/923/906/170/?TAP=1732",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Dolphin.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.223857499.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 28,
            category_id: "b",
            name: "GREEN TURTLE",
            image: "",
            scientificName: "Chelonia mydas",
            category: "Endangered",
            population: "90,000",
            habitat: "oceans",
            information: "The green turtle is one of the largest sea turtles and the only herbivore among the different species. Green turtles are in fact named for the greenish color of their cartilage and fat, not their shells. In the Eastern Pacific, a group of green turtles that have darker shells are called black turtles by the local community. Green turtles are found mainly in tropical and subtropical waters. Like other sea turtles, they migrate long distances between feeding grounds and the beaches from where they hatched. Classified as endangered, green turtles are threatened by overharvesting of their eggs, hunting of adults, being caught in fishing gear and loss of nesting beach sites.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/world-wildlife-fund-save-the-green-sea-turtles",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Green-Turtle.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.30180223.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 29,
            category_id: "b",
            name: "HECTOR'S DOLPHIN",
            image: "",
            scientificName: "Cephalorhynchus hectori",
            category: "Endangered",
            population: "7,000",
            habitat: "oceans",
            information: "Hector’s dolphins are the smallest and rarest marine dolphins in the world. They have distinct black facial markings, short stocky bodies and a dorsal fin shaped like a Mickey Mouse ear. There is a subspecies of Hector’s dolphin known as Maui’s dolphin that is critically endangered and estimated to have a population of only 55. They are found only in the shallow coastal waters along western shores of New Zealand’s North Island.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/help-out-our-beautiful-native-hector-s-dolphins-from-fishing-nets-protect-our-precious-pahu-and-sign-the-petition",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Dolphin.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.223210331.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 30,
            category_id: "b",
            name: "HUMPHEAD WRASSE",
            image: "",
            scientificName: "Cheilinus undulatus",
            category: "Endangered",
            population: "50% decrease",
            habitat: "oceans",
            information: "The humphead wrasse is an enormous coral reef fish—growing over six feet long—with a prominent bulge on its forehead. Some of them live to be over 30 years old. They roam through coral reefs in search of hard shelled prey such as mollusks, starfish, or crustaceans. \nWWF urges local governments in the Coral Triangle to stop the trade and consumption of humphead wrasse—one of the most expensive live reef fishes in the world. Live reef fish trade in Southeast Asia continues to be a significant problem that threatens the region’s food security as well as its reefs, as poachers often resort to legal and destructive fishing methods to catch them.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/noaa-help-save-the-humphead-wrasse-from-endangerment",
            donate: "https://www.marinebio.org/species/humphead-wrasses/cheilinus-undulatus/"
        },
        {
            id: 31,
            category_id: "b",
            name: "INDIAN ELEPHANT",
            image: "",
            scientificName: "Elephas maximus indicus",
            category: "Endangered",
            population: "20,000 – 25,000",
            habitat: "subtropical broadleaf forests, tropical broadleaf moist forests, dry forests, grassland",
            information: "Indian elephants may spend up to 19 hours a day feeding and they can produce about 220 pounds of dung per day while wandering over an area that can cover up to 125 square miles. This helps to disperse germinating seeds. They feed mainly on grasses, but large amounts of tree bark, roots, leaves and small stems are also eaten. Cultivated crops such as bananas, rice and sugarcane are favored foods as well. Since they need to drink at least once a day, these elephants are always close to a source of fresh water.",
            source: "worldwildlife.org",
            petition: "https://www.worldanimalprotection.ca/take-action/petition-amer-fort",
            donate: "https://join.wwfindia.org/save-elephant/"
        },
        {
            id: 32,
            category_id: "b",
            name: "INDUS RIVER DOLPHIN",
            image: "",
            scientificName: "Platanista minor",
            category: "Endangered",
            population: "1,816",
            habitat: "lower parts of the Indus River",
            information: "Indus river dolphins are believed to have originated in the ancient Tethys Sea. When the sea dried up approximately 50 million years ago, the dolphins were forced to adapt to its only remaining habitat—rivers. Today, they can only be found in the lower parts of the Indus River in Pakistan and in River Beas, a tributary of the Indus River in Punjab, India. In Pakistan, their numbers declined dramatically after the construction of an irrigation system, and most dolphins are confined to a 750 mile stretch of the river and divided into isolated populations by six barrages. They have adapted to life in the muddy river and are functionally blind. They rely on echolocation to navigate, communicate and hunt prey including prawns, catfish, and carp.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/940/822/914/protect-the-rare-and-endangered-indus-river-dolphin/",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Dolphin.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.96854111.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 33,
            category_id: "b",
            name: "IRRAWADDY DOLPHIN",
            image: "",
            scientificName: "Orcaella brevirostris",
            category: "Endangered",
            population: "89",
            habitat: "lakes, rivers, estuaries, and coasts",
            information: "Irrawaddy dolphins are found in coastal areas in South and Southeast Asia, and in three rivers: the Ayeyarwady (Myanmar), the Mahakam (Indonesian Borneo) and the Mekong. The Mekong River Irrawaddy dolphins inhabit a 118-mile stretch of the river between Cambodia and Lao PDR and are scarce—just 92 individuals are estimated to still exist. These dolphins have a bulging forehead, short beak, and 12-19 teeth on each side of both jaws.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/1/save-the-irrawaddy-dolphin-from-extinction/",
            donate: "https://burmadolphins.com/donate/"
        },
        {
            id: 34,
            category_id: "b",
            name: "MOUNTAIN GORILLA",
            image: "",
            scientificName: "Gorilla beringei beringei",
            category: "Endangered",
            population: "1,000",
            habitat: "high mountain forests",
            information: "As their name implies, mountain gorillas live in forests high in the mountains, at elevations of 8,000 to 13,000 feet. They have thicker fur, and more of it, compared to other great apes. The fur helps them to survive in a habitat where temperatures often drop below freezing. But as humans have moved more and more into the gorillas’ territory, the gorillas have been pushed farther up into the mountains for longer periods, forcing them to endure dangerous and sometimes deadly conditions. \nWhat might have been a bleak outlook for the subspecies just a couple of decades ago has brightened in recent years due to conservation efforts. Despite ongoing civil conflict, poaching and an encroaching human population, both populations of mountain gorillas have increased in numbers.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/164/209/904/save-the-mountain-gorilla/",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Gorilla.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.34450913.138606632.1655935991-1703178925.1655935991"
        },
        {
            id: 35,
            category_id: "b",
            name: "NORTH ATLANTIC RIGHT WHALE",
            image: "",
            scientificName: "Eubalaena glacialis",
            category: "Endangered",
            population: "366",
            habitat: "oceans",
            information: "The North Atlantic right whale can easily be identified by the white calluses on its head, which are very noticeable against the whale’s dark gray body. It has a broad back without a dorsal fin and a long arching mouth that begins above the eye. A baleen whale, it feeds by swimming through a swarm of plankton with its mouth open and the head slightly above the surface. Right whales are found more often in coastal waters, especially during the breeding season.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/u-s-national-oceanic-and-atmospheric-administration-petition-to-prevent-the-extinction-of-the-north-atlantic-right-whale",
            donate: "https://us.whales.org/whales-dolphins/how-we-help/saving-the-endangered-north-atlantic-right-whale/raise-your-right-hand/"
        },
        {
            id: 36,
            category_id: "b",
            name: "RED PANDA",
            image: "",
            scientificName: "Ailurus fulgens",
            category: "Endangered",
            population: "Less than 10,000",
            habitat: "temperate forests",
            information: "The red panda is slightly larger than a domestic cat with a bear-like body and thick russet fur. The belly and limbs are black, and there are white markings on the side of the head and above its small eyes. Red pandas are very skillful and acrobatic animals that predominantly stay in trees. Almost 50% of the red panda’s habitat is in the Eastern Himalayas. They use their long, bushy tails for balance and to cover themselves in winter, presumably for warmth. Primarily an herbivore, the name panda is said to come from the Nepali word ‘ponya', which means bamboo or plant eating animal.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/317/925/734/save-the-red-panda/",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Red-Panda.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.203807888.1470292348.1656191304-1703178925.1655935991"
        },
        {
            id: 37,
            category_id: "b",
            name: "SEA LION",
            image: "",
            scientificName: "Zalophus wollebaeki",
            category: "Endangered",
            population: "18,000",
            habitat: "oceans",
            information: "Sea lion, any of six species of eared seals found primarily in Pacific waters. Sea lions are characterized by a coat of short coarse hair that lacks a distinct undercoat. Except for the California sea lion (Zalophus californianus), males have lion-like manes and constantly roar to defend their harems (hence their name). \nUnlike the true, or earless, seals (family Phocidae), sea lions and other eared seals (family Otariidae) are able to rotate their hind flippers forward to use all four limbs when moving about on land. Sea lions also have longer flippers than true seals.",
            source: "britannica.com",
            petition: "https://www.change.org/p/joyce-murray-stop-the-west-coast-seal-slaughter-before-it-starts",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Sea-Lion.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.31923006.1470292348.1656191304-1703178925.1655935991"
        },
        {
            id: 38,
            category_id: "b",
            name: "SEI WHALE",
            image: "",
            scientificName: "Balaenoptera borealis",
            category: "Endangered",
            population: "80,000",
            habitat: "oceans",
            information: "The sei whale is one of the fastest whales, reaching speeds of up to 30 miles per hour. Sei whales inhabit all oceans and adjoining seas except in tropical and polar regions. Like other great whales, they prefer to spend the summer feeding in cooler waters before migrating to warmer waters to breed and give birth to their calves.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/595/292/999/help-save-the-sei-whale-from-the-hunt-in-japan/",
            donate: "https://uk.whales.org/whales-dolphins/species-guide/sei-whale/"
        },
        {
            id: 39,
            category_id: "b",
            name: "SRI LANKAN ELEPHANT",
            image: "",
            scientificName: "Elephas maximus maximus",
            category: "Endangered",
            population: "2,500 - 4,000",
            habitat: "tropical and subtropical moist broadleaf forests",
            information: "The Sri Lankan subspecies is the largest and also the darkest of the Asian elephants, with patches of depigmentation—areas with no skin color—on its ears, face, trunk and belly. Once found throughout the tear-shaped island at the bottom of India’s southern tip, these elephants are now being pushed into smaller areas as development activities clear forests and disrupt their ancient migratory routes. \nThe herd size in Sri Lanka ranges from 12-20 individuals or more. It is led by the oldest female, or matriarch. In Sri Lanka, herds have been reported to contain nursing units, consisting of lactating females and their young, and juvenile care units, containing females with juveniles. The Sri Lankan elephant population has fallen almost 65% since the turn of the 19th century. Today, the Sri Lanka elephant is protected under the Sri Lankan law and killing one carries the death penalty.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/president-of-sri-lanka-stop-the-torture-and-exploitation-of-further-elephants-in-sri-lanka",
            donate: "https://www.slwcs.org/donate"
        },
        {
            id: 40,
            category_id: "b",
            name: "TIGER",
            image: "",
            scientificName: "Panthera tigris",
            category: "Endangered",
            population: "3,900",
            habitat: "tropical rainforests, evergreen forests, temperate forests, mangrove swamps, grasslands, savannas",
            information: "There are two recognized subspecies of tiger*: the continental (Panthera tigris tigris) and the Sunda (Panthera tigris sondaica). The largest of all the Asian big cats, tigers rely primarily on sight and sound rather than smell for hunting. They typically hunt alone and stalk prey. A tiger can consume more than 80 pounds of meat at one time. On average, tigers give birth to two to four cubs every two years. If all the cubs in one litter die, a second litter may be produced within five months. \nTigers generally gain independence at around two years of age and attain sexual maturity at age three or four for females and four or five years for males. Juvenile mortality is high, however—about half of all cubs do not survive more than two years. Tigers have been known to reach up to 20 years of age in the wild. \nMales of the larger subspecies, the continental tiger, may weigh up to 660 pounds. For males of the smaller subspecies—the Sunda tiger—the upper range is at around 310 pounds. Within both subspecies, males are heavier than females. \nTigers are mostly solitary, apart from associations between mother and offspring. Individual tigers have a large territory, and the size is determined mostly by the availability of prey. Individuals mark their domain with urine, feces, rakes, scrapes, and vocalizing. \nAcross their range, tigers face unrelenting pressures from poaching, retaliatory killings, and habitat loss. They are forced to compete for space with dense and often growing human populations.",
            source: "worldwildlife.org",
            petition: "https://www.bornfree.org.uk/tiger-farming-petition",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Tiger"
        },
        {
            id: 41,
            category_id: "b",
            name: "WHALE SHARK",
            image: "",
            scientificName: "Rhincodon typus",
            category: "Endangered",
            population: "119,000 – 238,000",
            habitat: "oceans",
            information: "Whale sharks (Rhincodon typus) are the largest shark, and indeed largest of any fishes alive today. They feed on plankton and travel large distances to find enough food to sustain their huge size, and to reproduce. Whale sharks are found in all the tropical oceans of the world. Their white spotted colouration makes these gentle giants easy to distinguish, and popular with snorkelers and divers at sites where they aggregate off the coast. \nThe maximum size of whale sharks is not known, but could be as large as 20m. Females give birth to live young but this has never been observed. Where pupping occurs and where the youngest animals situate remains a mystery, as they are very rarely found. Adults are often found feeding at the surface, but may dive to 1000m. Whale sharks are protected from fishing in many countries these days, but are in decline in some areas.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/713/226/905/save-whale-sharks/",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Whale-Shark.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.30792511.1470292348.1656191304-1703178925.1655935991"
        },
        {
            id: 42,
            category_id: "c",
            name: "BLACK SPIDER MONKEY",
            image: "",
            scientificName: "Ateles paniscus",
            category: "Vulnerable",
            population: "Less than 3,000",
            habitat: "tropical and subtropical moist broadleaf forests",
            information: "The black spider monkey—also known as the Guiana or red-faced spider monkey—is found in eastern South America in areas north of the Amazon River. They are one of seven species of spider monkeys found in Latin America and one of the largest primate species in South America.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/537/770/043/protect-endangered-black-spider-monkeys/",
            donate: "https://ptes.org/grants/worldwide-projects/protecting-the-critically-endangered-colombian-black-spider-monkeys/"
        },
        {
            id: 43,
            category_id: "c",
            name: "DUGONG",
            image: "",
            scientificName: "Dugong dugon",
            category: "Vulnerable",
            population: "200",
            habitat: "oceans",
            information: "Dugongs are cousins of manatees and share a similar plump appearance, but have a dolphin fluke-like tail. And unlike manatees, which use freshwater areas, the dugong is strictly a marine mammal. Commonly known as 'sea cows', dugongs graze peacefully on sea grasses in shallow coastal waters of the Indian and western Pacific Oceans.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/takeaction/361/244/102/",
            donate: "https://www.terracyclefoundation.org/pages/dugong"
        },
        {
            id: 44,
            category_id: "c",
            name: "GIANT PANDA",
            image: "",
            scientificName: "Ailuropoda melanoleuca",
            category: "Vulnerable",
            population: "1,864",
            habitat: "temperate broadleaf and mixed forests of southwest China",
            information: "The panda, with its distinctive black and white coat, is adored by the world and considered a national treasure in China. This bear also has a special significance for WWF because it has been our logo since our founding in 1961. \nPandas live mainly in temperate forests high in the mountains of southwest China, where they subsist almost entirely on bamboo. They must eat around 26 to 84 pounds of it every day, depending on what part of the bamboo they are eating. They use their enlarged wrist bones that function as opposable thumbs. \nA newborn panda is about the size of a stick of butter—about 1/900th the size of its mother—but females can grow up to about 200 pounds, while males can grow up to about 300 pounds as adults. These bears are excellent tree climbers despite their bulk.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/nationalpandaday-there-are-9-pandas-in-the-us-yaya-lele-held-captive-at-memphis-zoo-suffer-from-parasites-mental-distress-low-quality-bamboo-and-a-lack-of-nutrition-join-pandavoicesorg-idausa-to-support-saveyayalele-with-a-tweetstorm-now",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Panda"
        },
        {
            id: 45,
            category_id: "c",
            name: "GIANT TORTOISE",
            image: "",
            scientificName: "Chelonoidis niger",
            category: "Vulnerable",
            population: "60,000",
            habitat: "dry lowlands of the Galapagos Islands",
            information: "There are many subspecies of giant tortoises that are found on different islands and have different appearances. Those that live on the larger islands where there is more rain have “dome” shaped shells, while those that live in drier conditions are smaller tortoises and have a “saddleback” shell. \nOn June 24, 2012, the world-famous giant tortoise affectionately known as “Lonesome George” passed away. He was the last surviving land tortoise from Pinta Island, one of the northern islands in the Galápagos. Thought to be 100 years old, Lonesome George lived at the Charles Darwin Research Station since he was found in 1971. For more than three decades, the Galápagos National Park tried to save the Pinta subspecies by finding George a mate. Unfortunately they did not succeed. Sadly with Lonesome George’s passing, there will be no more Pinta Island tortoises.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/takeaction/472/502/549/",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Giant-Tortoise.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.146835895.1803783243.1656375742-1703178925.1655935991"
        },
        {
            id: 46,
            category_id: "c",
            name: "GREAT WHITE SHARK",
            image: "",
            scientificName: "Carcharodon carcharias",
            category: "Vulnerable",
            population: "3,500",
            habitat: "oceans",
            information: "The great white shark is the world's largest known predatory fish. It has 300 teeth, yet does not chew its food. Sharks rip their prey into mouth-sized pieces which are swallowed whole. The shark’s heavy, torpedo-shaped body allows it to cruise efficiently for long periods of time, and then suddenly switch to high speed bursts in pursuit of prey—sometimes leaping out of the water. It feeds on a broad spectrum of prey, from small fish, such as halibut, to large seals and dolphins.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/united-nations-ban-killing-great-white-sharks",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/species-adoptions/great-white-shark.aspx"
        },
        {
            id: 47,
            category_id: "c",
            name: "GREATER ONE-HORNED RHINO",
            image: "",
            scientificName: "Rhinoceros unicornis",
            category: "Vulnerable",
            population: "3,700",
            habitat: "tropical and subtropical grasslands, savannas, and shrublands",
            information: "The greater one-horned rhino (or “Indian rhino”) is the largest of the rhino species. Once widespread across the entire northern part of the Indian sub-continent, rhino populations plummeted as they were hunted for sport or killed as agricultural pests. This pushed the species very close to extinction and by the start of the 20th century, around 200 wild greater one-horned rhinos remained. \nThe recovery of the greater one-horned rhino is among the greatest conservation success stories in Asia. Thanks to strict protection and management from Indian and Nepalese wildlife authorities, the greater one-horned rhino was brought back from the brink. Today populations have increased to around 3,700 rhinos in northeastern India and the Terai grasslands of Nepal. \nThe greater one-horned rhino is identified by a single black horn about 8-25 inches long and a grey-brown hide with skin folds, which gives it an armor-plated appearance. The species is solitary, except when adult males or rhinos nearing adulthood gather at wallows or to graze. Males have loosely defined home ranges that are not well defended and often overlap. They primarily graze, with a diet consisting almost entirely of grasses as well as leaves, branches of shrubs and trees, fruit, and aquatic plants.",
            source: "worldwildlife.org",
            petition: "https://therainforestsite.greatergood.com/clicktogive/trs/petition/ban-rhino-horn-trade",
            donate: "https://wwf.ca/stories/armoured-yet-vulnerable/"
        },
        {
            id: 48,
            category_id: "c",
            name: "HIPPOPOTAMUS",
            image: "",
            scientificName: "Hippopotamus amphibius",
            category: "Vulnerable",
            population: "115,000 to 130,000",
            habitat: "rivers and lakes throughout sub-Saharan Africa",
            information: "The hippopotamus, also known as the “river horse,” lives along the rivers and lakes throughout sub-Saharan Africa. Weighing up to 8,000 pounds, the hippo is the heaviest land animal after the elephant. Hippos seek refuge from the heat by living in water during the day, and at night they come ashore to feed on short, soft grasses and fallen fruit. The eyes and ears of a hippopotamus are on top of its head, so it can keep watch for enemies—mainly crocodiles—while lying low in the water. These giants are currently at risk from habitat loss.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/takeaction/703/902/923/",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Hippopotamus.aspx?sc=AWY1800OQ18317A01909RX&_ga=2.218351897.1803783243.1656375742-1703178925.1655935991"
        },
        {
            id: 49,
            category_id: "c",
            name: "LEATHERBACK TURTLE",
            image: "",
            scientificName: "Dermochelys coriacea",
            category: "Vulnerable",
            population: "3,000",
            habitat: "oceans",
            information: "Leatherback turtles are named for their shell, which is leather-like rather than hard, like other turtles. \nThey are the largest sea turtle species and also one of the most migratory, crossing both the Atlantic and Pacific Oceans. Pacific leatherbacks migrate from nesting beaches in the Coral Triangle all the way to the California coast to feed on the abundant jellyfish every summer and fall. \nAlthough their distribution is wide, numbers of leatherback turtles have seriously declined during the last century as a result of intense egg collection and fisheries bycatch. Globally, leatherback status according to IUCN is listed as Vulnerable, but many subpopulations (such as in the Pacific and Southwest Atlantic) are Critically Endangered.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/noaa-save-the-sea-turtles",
            donate: "https://www.leatherback.org/"
        },
        {
            id: 50,
            category_id: "c",
            name: "LOGGERHEAD TURTLE",
            image: "",
            scientificName: "Caretta caretta",
            category: "Vulnerable",
            population: "Unknown",
            habitat: "oceans",
            information: "Loggerhead turtles are named for their large heads that support powerful jaw muscles, allowing them to crush hard-shelled prey like clams and sea urchins. They are less likely to be hunted for their meat or shell compared to other sea turtles. Bycatch, the accidental capture of marine animals in fishing gear, is a serious problem for loggerhead turtles because they frequently come in contact with fisheries. \nLoggerheads are the most common turtle in the Mediterranean, nesting on beaches from Greece and Turkey to Israel and Libya. Many of their nesting beaches are under threat from tourism development. Sea turtles are the living representatives of a group of reptiles that has existed on Earth and travelled our seas for the last 100 million years. They are a fundamental link in marine ecosystems and help maintain the health of coral reefs and sea grass beds.",
            source: "worldwildlife.org",
            petition: "https://act.seaturtles.org/page/21989/petition/1?ea.tracking.id=action%20center",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Loggerhead-Turtle.aspx"
        },
        {
            id: 51,
            category_id: "c",
            name: "MARINE IGUANA",
            image: "",
            scientificName: "Amblyrhynchus cristatus",
            category: "Vulnerable",
            population: "250,000",
            habitat: "oceans",
            information: "One of the main nesting zones for iguanas is located on a central tourist beach in the waterfront area of Puerto Villamil on Isabela Island. For several years, the Galápagos National Park protected only the central part of the nesting zone. In 2012, WWF, the Municipality of Isabela and the Charles Darwin Foundation extended the protected area to include the entire nesting zone. As part of this effort, additional signs for both tourists and local communities inform them about the importance of this nesting zone. A temporary fence was also built to protect the area and allow iguanas to pass through.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/coach-austin-save-marine-iguanas-788c93f0-2c5a-41d1-961b-5c35ba26076c",
            donate: "https://galapagosconservation.org.uk/wildlife/marine-iguana/"
        },
        {
            id: 52,
            category_id: "c",
            name: "OLIVE RIDLEY TURTLE",
            image: "",
            scientificName: "Lepidochelys olivacea",
            category: "Vulnerable",
            population: "2,500",
            habitat: "oceans",
            information: "The name for this sea turtle is tied to the color of its shell—an olive green hue. They are currently the most abundant of all sea turtles. Their vulnerable status comes from the fact that they nest in a very small number of places, and therefore any disturbance to even one nest beach could have huge repercussions on the entire population.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/350/752/522/demand-protection-for-the-mexican-ridley-turtle/",
            donate: "https://oliveridleyproject.org/"
        },
        {
            id: 53,
            category_id: "c",
            name: "POLAR BEAR",
            image: "",
            scientificName: "Ursus maritimus",
            category: "Vulnerable",
            population: "22,000 - 31,000",
            habitat: "Arctic Ocean, sea ice, and adjacent coastal areas",
            information: "The largest bear in the world and the Arctic's top predator, polar bears are a powerful symbol of the strength and endurance of the Arctic. The polar bear's Latin name, Ursus maritimus, means 'sea bear'. It's an apt name for this majestic species, which spends much of its life in, around, or on the ocean–predominantly on the sea ice. In the United States, Alaska is home to two polar bear subpopulations. \nConsidered talented swimmers, polar bears can sustain a pace of six miles per hour by paddling with their front paws and holding their hind legs flat like a rudder. They have a thick layer of body fat and a water-repellent coat that insulates them from the cold air and water. \nPolar bears spend over 50% of their time hunting for food. A polar bear might catch only one or two out of 10 seals it hunts, depending on the time of year and other variables. Their diet mainly consists of ringed and bearded seals because they need large amounts of fat to survive.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/676/149/345/demand-increased-protection-for-vulnerable-arctic-polar-bears/?TAP=1732",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Polar-Bear"
        },
        {
            id: 54,
            category_id: "c",
            name: "SNOW LEOPARD",
            image: "",
            scientificName: "Panthera uncia",
            category: "Vulnerable",
            population: "4,000 - 6,500",
            habitat: "high mountains",
            information: "The snow leopard’s powerful build allows it to scale great steep slopes with ease. Its hind legs give the snow leopard the ability to leap six times the length of its body. A long tail enables agility, provides balance and wraps around the resting snow leopard as protection from the cold. \nFor millennia, this magnificent cat was the king of the mountains. The mountains were rich with their prey such as blue sheep, Argali wild sheep, ibex, marmots, pikas and hares. The snow leopard’s habitat range extends across the mountainous regions of 12 countries across Asia: Afghanistan, Bhutan, China, India, Kazakhstan, Kyrgyz Republic, Mongolia, Nepal, Pakistan, Russia, Tajikistan, and Uzbekistan. The total range covers an area of close to 772,204 square miles, with 60% of the habitat found in China. However, more than 70% of snow leopard habitat remains unexplored. Home range sizes can vary from 4.6-15.4 square miles in Nepal to over 193 square miles in Mongolia. And population density can range from <0.1 to 10 or more individuals per 38.6 square miles, depending on prey densities and habitat quality. Nevertheless, the snow leopard population is very likely declining.",
            source: "worldwildlife.org",
            petition: "https://therainforestsite.greatergood.com/clicktogive/trs/petition/snow-leopards",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Snow-Leopard.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.218720665.1803783243.1656375742-1703178925.1655935991"
        },
        {
            id: 55,
            category_id: "c",
            name: "SOUTHERN ROCKHOPPER PENGUIN",
            image: "",
            scientificName: "Eudyptes chrysocome",
            category: "Vulnerable",
            population: "2,000,000",
            habitat: "oceans and coasts",
            information: "Much smaller in size than the emperor penguin, rockhopper penguins weigh less than 10 pounds. They were named for their distinctive hopping movements over the rocky hills and cliffs where they live and breed. In the last 30 years, it is estimated that the population of rockhoppers has fallen by nearly 25%—and now climate change could place them at even greater risk.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/regional-fisheries-bodies-save-endangered-penguins-from-fisheries-bycatch-and-overfishing?recruiter=419177630&recruited_by_id=4db42050-82b5-11e5-8115-df61ecdcfefb&utm_source=share_petition&utm_medium=copylink&utm_campaign=petition_dashboard",
            donate: "https://oceana.org/marine-life/southern-rockhopper-penguin/"
        },
        {
            id: 56,
            category_id: "d",
            name: "BELUGA",
            image: "",
            scientificName: "Delphinapterus leucas",
            category: "Near Threatened",
            population: "150,000",
            habitat: "oceans",
            information: "Belugas are extremely sociable mammals that live, hunt and migrate together in pods, ranging from a few individuals to hundreds of whales. Their bulbous forehead, called a 'melon', is flexible and capable of changing shape. This allows them to make different facial expressions. Belugas can produce a series of chirps, clicks, whistles and squeals, which give the beluga its other name, 'the canary of the sea'. They may sound like music or even nonsense to us, but to fellow belugas they convey important information. \nMany populations of belugas migrate as the sea ice changes in the Arctic. They move south in the fall as the ice forms and then return to feed again in the spring, as the ice breaks up. They can also be found near river mouths, and sometimes even venture up river. Belugas feed on a variety of fish species, such as salmon and herring, as well as shrimp, crabs and mollusks.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/the-honourable-bernadette-jordan-stop-marineland-from-exporting-belugas-whales-to-the-united-states",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Beluga-Whale.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.222463131.1803783243.1656375742-1703178925.1655935991"
        },
        {
            id: 57,
            category_id: "d",
            name: "GREATER SAGE-GROUSE",
            image: "",
            scientificName: "Centrocercus urophasianus",
            category: "Near Threatened",
            population: "100,000 to 500,000",
            habitat: "grasslands",
            information: "Greater sage-grouse were once found across 13 western U.S. states and 3 Canadian provinces. Unfortunately, because of oil and gas development, conversion of land for agricultural use, climate change and human development, sage-grouse only inhabit half their historic range. Well known for their spectacular mating dances performed on specific mating grounds called 'leks', these large birds are icons in the western U.S. and Canada.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/take-action-time-is-running-out-to-protect-sage-grouse-and-other-wyoming-wildlife?source_location=topic_page",
            donate: "https://www.sagegrouseinitiative.com/take-action/"
        },
        {
            id: 58,
            category_id: "d",
            name: "JAGUAR",
            image: "",
            scientificName: "Panthera onca",
            category: "Near Threatened",
            population: "15,000",
            habitat: "forests, grasslands",
            information: "Jaguars are strong swimmers and climbers and require large areas of tropical rain forest and stretches of riverbank to survive. Hunting and habitat loss due to deforestation continue to threaten the survival of these marvelous cats. WWF has worked with the government of Brazil to successfully protect large blocks of Amazon forest for the jaguar. In Peru, WWF continues to track jaguars to learn more about their habitat requirements.",
            source: "worldwildlife.org",
            petition: "https://www.thejaguarking.org/petition",
            donate: "https://support.worldwildlife.org/site/Donation2?df_id=15498&15498.donation=form1&s_src=AWS2101OQ18316A04237RX&S_subrc=web_HYCH&_ga=2.253398153.1803783243.1656375742-1703178925.1655935991"
        },
        {
            id: 59,
            category_id: "d",
            name: "MOUNTAIN PLOVER",
            image: "",
            scientificName: "Charadrius montanus",
            category: "Near Threatened",
            population: "15,000 - 20,000",
            habitat: "grasslands",
            information: "Mountain plovers are one of only 12 grassland birds endemic to the western Great Plains. They nest across the western Great Plains and Rocky Mountain states, from the Canadian border to northern Mexico, and winter in California, southern Arizona, Texas and Mexico. Mountain plovers only nest in areas with sparse vegetation or bare ground, such as prairie dog towns. Loss of these areas because of crop planting or the removal of prairie dogs, is the biggest threat to the mountain plover's population.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/oshmerch-osh-com-rid-shelves-of-neonicotinoids-to-keep-our-birds-singing",
            donate: "https://abcbirds.org/bird/mountain-plover/"
        },
        {
            id: 60,
            category_id: "d",
            name: "PLAINS BISON",
            image: "",
            scientificName: "Bison bison bison",
            category: "Near Threatened",
            population: "20,504",
            habitat: "grasslands",
            information: "Prior to European colonization plains bison are estimated to have numbered between 30million-60 million animals and were the widest-ranging large mammal in North America. Bison were (and remain) central in the lives and traditions of many Native nations and an umbrella species for many plants and animals sharing its habitat. By 1889, only 512 plains bison remained after the ravages of westward expansion, market demand, and a deliberate effort by the US Government to eliminate the bison in order subdue the Native people that relied so heavily upon them. In response to their tragic decline, conservationists and Indigenous peoples successfully brought the plains bison back from the brink of extinction. \nThanks to their efforts, by 1935 the population had risen to approximately 20,000 bison, and many were restored as wildlife to refuges and parks throughout North America. In honor of the role that this majestic species plays as an icon for the lands and people of the United States, the bison was formally designated the national mammal in 2016. However, much work remains much work to do to see bison restored where they are embraced. In fact, the number of bison held in “conservation herds” is currently no greater than it was in 1935.",
            source: "worldwildlife.org",
            petition: "https://www.change.org/p/debra-a-haaland-support-endangered-species-act-protection-for-yellowstone-s-wild-american-bison-herds-a55e40d3-c5ef-4467-84bc-324f8502a006",
            donate: "https://gifts.worldwildlife.org/gift-center/gifts/Species-Adoptions/Bison.aspx?sc=AWY1705OQ18316A01275RX&_ga=2.152602681.1803783243.1656375742-1703178925.1655935991"
        },
        {
            id: 61,
            category_id: "d",
            name: "WHITE RHINO",
            image: "",
            scientificName: "Ceratotherium simum",
            category: "Near Threatened",
            population: "18,000",
            habitat: "long and short grass savanna areas in grasslands",
            information: "White rhinos are the second-largest land mammal and their name comes from the Afrikaan’s, a West Germanic language, word “weit” which means wide and refers to the animal’s mouth. Also known as the square-lipped rhinoceros, white rhinos have a square upper lip with almost no hair. Two genetically different subspecies exist the northern and southern white rhino, and are found in two different regions in Africa. As of March 2018, there are only two rhinos of the northern white rhino left, both of which are female. They live in the Ol Pejeta Conservancy in Kenya and are protected round-the-clock by armed guards. Their near extinction is due to decades of rampant poaching for rhino horn. \nThe majority (98.8%) of the southern white rhinos occur in just four countries: South Africa, Namibia, Zimbabwe, and Kenya. Southern white rhinos were thought to be extinct in the late 19th century, but in 1895 a small population of fewer than 100 individuals was discovered in Kwazulu-Natal, South Africa. After more than a century of protection and management, they are now classified as Near Threatened and around 18,000 animals exist in protected areas and private game reserves. They are the only of the five rhino species that are not endangered. \nWhite rhinos have complex social structures. Groups of sometimes 14 rhinos may form, notably females with calves. Adult males defend territories of roughly one square mile, which they mark with vigorously scraped dung piles. The home range for adult females can be more than seven times larger, depending on habitat quality and population density. Breeding females are prevented from leaving a dominant male’s territory, which is marked and patrolled by its owner on a regular basis. Males competing for a female may engage in serious conflict, using their horns and massive size to inflict wounds.",
            source: "worldwildlife.org",
            petition: "https://www.thepetitionsite.com/774/715/623/save-the-northern-white-rhino-from-extinction/",
            donate: "https://rhinos.org/help-rhinos/ways-to-give/"
        }
    ];

    await knex('categories').insert(categories);
    await knex('species').insert(species);

}